import Head from 'next/head'
import Layout from '../Components/Layout/Layout';
import UserList from '../Components/Userlist'

export default function Home() {

  return (
    <>
      <Head>
        <title>Cms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <UserList/>
        </Layout>
      </main>
    </>
  )
}
